language: node_js
node_js:
 - "stable"

services:
 - postgresql

install:
 - npm install

cache:
  directories:
   - "cache"

before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build

after_script:
 - nyc report --reporter=text-lcov | coveralls
 - ./cc-test-reporter after-build --coverage-endpoint "https://api.codeclimate.com/v1/test_reports"