language: node_js
node_js:
 - "stable"

services:
 - postgresql

install:
 - npm install

cache:
  directories:
  - "cache"

before_script:
 - psql -c 'create database travis_ci_test;' -u postgres

after_script:
  - nyc report --reporter=text-lcov | coveralls